Add Class Speed
IlyaBozh/First-repository pull request #1
Opened 2021-07-20 16:37 UTC by IlyaBozh

2021-07-20 17:44 UTC, SoraRise commented
File "showSpeed" is empty.

2021-07-20 17:53 UTC, Cosmostas requested changes

2021-07-20 17:53 UTC, Cosmostas commented on Task1/src/showSpeed.kt
> +class Speed(_speed: Int){
Delete underscore - it's not kotlin code style

2021-07-20 17:53 UTC, Cosmostas commented on Task1/src/showSpeed.kt
> +    val speed = _speed
Try to use data class
It's take from u necessary to init var's

2021-07-20 17:53 UTC, Cosmostas commented on Task1/src/showSpeed.kt
> +        println("Your speed now $speed ")
This statement sound's weird.  Add more Grammar: Now speed u'r speed is $speed. Something like this. If u wont write in this case. Why "You"? No in every case it's a speed same object that call this method.

2021-07-20 22:50 UTC, SoraRise commented on Task1/src/showSpeed.kt
> +class Speed(speed: Int){
Класс не должен принимать в себя данные.

2021-07-20 22:51 UTC, SoraRise commented on Task1/src/showSpeed.kt
> +    val humanSpeed = speed
Зачем ты инициализируешь переменную, если ты передаёшь её в сигнатуру метода ? 
У тебя метод принимает скорость, зачем тебе дополнительная инициализация. Если я не прав или не понял тебя, в личку :3

2021-07-21 06:43 UTC, Cosmostas commented on Task1/src/showSpeed.kt
> +class Speed(speed: Int){
On English please.
And class can get var's. It's default constructor

2021-07-21 10:00 UTC, Cosmostas approved these changes

2021-07-21 10:00 UTC, Cosmostas commented on Task1/src/main.kt
> +    val human: Speed = Speed(12)
there is no need to specify the data type.  the compiler will detect this automatically

2021-07-21 10:12 UTC, merged